name: rewards_network_shared
description: A new Flutter application.
publish_to: 'none' 

version: 1.0.1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:

flutter:
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  #
  
  
